using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LeaderBoard : MonoBehaviour
{
    public static LeaderBoard instance = null;

    private List<Player> playerList;

    //Awake is always called before any Start functions
    void Awake()
    {
        //Check if instance already exists
        if (instance == null)

            //if not, set instance to this
            instance = this;

        //If instance already exists and it's not this:
        else if (instance != this)

            //Then destroy this. This enforces our singleton pattern, meaning there can only ever be one instance of a GameManager.
            Destroy(gameObject);

        //Sets this to not be destroyed when reloading scene
        DontDestroyOnLoad(gameObject);

        playerList = new List<Player>();
    }

    // Use this for initialization
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    public void addPlayer(Player player)
    {
        playerList.Add(player);

        playerList.Sort(delegate (Player c1, Player c2) { return c1.getTime().CompareTo(c2.getTime()); });

        LeaderBoardUI.instance.printLeaderBoard(playerList);
    }
}
